version: '3'

services:
##########elasticsearch##########
    elasticsearch:
      container_name: elasticsearch
      build: ./elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "9200:9200"
        - "9300:9300"
##########nginx##########
    nginx:
      container_name: nginx
      build: ./nginx
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro # nginx proxy settings 
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # nginx conf file
        - ./nginx/ssl:/etc/nginx/ssl # if uses ssl
        - ./nginx/log:/var/log/nginx/ # nginx log location

      ports:
        - "80:80" # http
        - "443:443" # https
##########logstash##########
    logstash:
      container_name: logstash
      build: ./logstash
      volumes:
        - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ./nginx/log/cherrypick_co_kr_access.log:/usr/share/logstash/pipeline/cherrypick_co_kr_access.log
      command: logstash -f /usr/share/logstash/pipeline/logstash.conf
      ports:
        - "5000:5000"
        - "9600:9600"
##########mysql##########
    mysql:
      build: ./mysql
      volumes:
        - ./mysql/db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: PASSWORD
        MYSQL_DATABASE: DATABASE
        MYSQL_USER: USER
        MYSQL_PASSWORD: PASSWORD
      ports:
        - "3306:3306"
##########ghost##########
    ghost:
      build: ./ghost
      volumes:
        - ./ghost/ghost_data:/var/lib/ghost/content
      ports:
        - "2368:2368"
      environment:
        NODE_ENV: production
        database__client: #UPDATE ME
        database__connection__host: #UPDATE ME
        database__connection__user: #UPDATE ME
        database__connection__password: #UPDATE ME
        database__connection__database: #UPDATE ME

##########jenkins##########
    jenkins:
      build: ./jenkins
      volumes:
        - ./jenkins/jenkins_data:/var/jenkins_home
      ports:
        - "8080:8080"
